export const projectList = [
    {
        "projectId": "1",
        "projectName": "Distance Measurement",
        "projectHeader": "Redefining The Art of Spatial Awareness in Machines.",
        "projectStack": ["Python", "OpenCV", "Sobel Edge Detection"],
        "framework": [],
        "projectURL": "https://github.com/faizzmi/distance-measurement",
        "projectLevel":"Final Year Project",
        "createdAt": "2024-02-04T03:10:42Z",
        "projectType": "Computer Vision",
        "projectFeatures": "This project focused on implementing real-time distance measurement using edge detection, specifically with Sobel edge detection. One of the most challenging aspects was accurately detecting and calculating distances under varying lighting conditions and edge complexities. The project required the combination of computer vision techniques and real-time processing, which helped refine my understanding of image processing and spatial recognition. Implementing this with Python and OpenCV was both rewarding and challenging as it involved continuous testing to ensure precision and accuracy in measurement.",
        "reflection": "Working on this project was a tremendous learning experience in the field of computer vision. It allowed me to dive deep into the practical application of edge detection algorithms and real-time data processing. The main takeaway was understanding how to handle challenges related to variable lighting and object detection, which often lead to inaccuracies. This hands-on experience strengthened my problem-solving skills and gave me the confidence to work with OpenCV in future machine vision projects. The project was both technically demanding and rewarding as it involved translating theory into working code, providing valuable insight into spatial awareness and distance calculation.",
        "projectDesc": "This project aimed to develop a system for real-time distance measurement using computer vision techniques. It utilized Sobel edge detection to identify and analyze object boundaries within images. The primary challenges involved ensuring accurate distance calculations under varying lighting conditions and dealing with complex edge scenarios. The project successfully demonstrated the application of computer vision principles for spatial awareness and distance measurement."
    },
    {
        "projectId": "2",
        "projectName": "Foody",
        "projectHeader": "Transforming Food Delivery Into A Seamless Revolution.",
        "projectStack": ["PHP", "MySQL", "HTML", "CSS", "JavaScript"],
        "framework": ["Laravel"],
        "projectURL": "https://github.com/faizzmi/Foody",
        "projectLevel":"Academic",
        "createdAt": "2024-11-09T14:56:03Z",
        "projectType": "Web Development",
        "projectFeatures": "Foody was a project aimed at revolutionizing food delivery by combining food ordering and real-time delivery tracking into a seamless user experience. One of the key features was integrating a delivery tracking system, ensuring customers could track their orders from preparation to arrival. The most significant challenge was ensuring that the real-time updates of order statuses were reflected immediately for both the customer and the restaurant. I used Laravel for backend development, which enabled smooth management of user data, payment processing, and order handling. A critical part of the project was ensuring the database structure and API endpoints were efficient enough to handle large amounts of user traffic during peak times, which was a tough yet rewarding hurdle to overcome.",
        "reflection": "Developing Foody was a valuable learning experience, particularly in backend development with PHP and Laravel. It allowed me to dive deeper into database management and real-time systems, reinforcing the importance of efficient code and architecture. The project gave me a deeper understanding of how complex web applications are structured, particularly how frontend and backend systems interact. Handling real-time order tracking and integrating payment processing presented challenges that I hadn’t encountered before, which ultimately helped me grow as a full-stack developer. The experience also honed my problem-solving abilities, as I had to optimize the user experience to ensure it was smooth and scalable.",
        "projectDesc": "Foody is a web application designed to streamline the food delivery process. It integrates online food ordering with real-time delivery tracking, providing a seamless experience for both customers and restaurants. Key features include order management, payment processing, and real-time status updates. The project emphasizes user experience and efficiency, aiming to improve the overall food delivery process."
    },
    {
        "projectId": "3",
        "projectName": "VisionSense",
        "projectHeader": "Unlocking The Future Of Personalized Lens Fitting.",
        "projectStack": ["Python"],
        "framework": [],
        "projectURL": "https://github.com/faizzmi/Fuzzy-Logic-Based-Contact-Lenses-Recommendation-System",
        "projectLevel":"Academic",
        "createdAt": "2024-11-09T14:56:03Z",
        "projectType": "Machine Learning",
        "projectFeatures": "VisionSense utilized fuzzy logic to recommend personalized contact lenses based on a user's eye data. The project’s unique approach was using fuzzy rules to take into account various subjective factors like comfort and fit, alongside objective data such as eye measurements. A major challenge was fine-tuning these fuzzy rules to ensure the system provided accurate and suitable recommendations. Another significant aspect was gathering and processing the input data from users, which required careful attention to detail. The project applied machine learning principles and demonstrated how AI could personalize healthcare, specifically in the area of optical lenses.",
        "reflection": "This project was an eye-opener into the practical applications of machine learning and fuzzy logic. The most challenging part was refining the fuzzy logic rules and ensuring the recommendations were genuinely beneficial to the user. I gained valuable experience in using Python for machine learning tasks, and this project helped improve my understanding of how machine learning algorithms can be applied to real-world problems. Working with fuzzy logic was a unique experience as it gave me the opportunity to explore non-traditional approaches to problem-solving. Overall, this project enriched my knowledge in AI and data processing, especially in personalized health recommendations.",
        "projectDesc": "VisionSense is a machine learning-based system that recommends personalized contact lenses to users. It utilizes fuzzy logic to consider both objective eye measurements and subjective factors like comfort and fit. The system aims to provide tailored recommendations for optimal vision correction and user satisfaction."
    },
    {
        "projectId": "4",
        "projectName": "GadgetVerse",
        "projectHeader": "Step Into A Realm Where Technology Meets Infinite Possibilities.",
        "projectStack": ["JavaScript"],
        "framework": ["React.JS", "Three.JS", "Tailwind.Css"],
        "projectURL": "https://github.com/faizzmi/GadgetVerse",
        "projectLevel":"Personal",
        "createdAt": "2024-12-24T16:18:31Z",
        "projectType": "Web Development",
        "projectFeatures": "GadgetVerse was built to showcase tech products in an interactive 3D environment. The challenge was integrating 3D rendering into the web in a way that was both visually appealing and performance-optimized. By using Three.js for 3D models and React.js for dynamic user interfaces, I was able to create a smooth user experience. The primary challenge was ensuring the website remained responsive and fast despite the complexity of rendering 3D models. It required a lot of optimization work, especially in minimizing loading times and handling large models without compromising quality. Another key feature was the integration of Tailwind CSS for styling, which allowed for quick and scalable UI designs.",
        "reflection": "Building GadgetVerse was a truly transformative experience in web development. It expanded my knowledge of interactive web applications and 3D rendering. One of the biggest takeaways was learning how to manage complex interactions in a web environment while keeping performance optimized. The project also introduced me to the challenges of integrating advanced technologies like Three.js and React in a way that was user-friendly and scalable. It was a great exercise in balancing visual appeal with technical constraints, and I feel much more confident in creating immersive, interactive web experiences after completing it.",
        "projectDesc": "GadgetVerse is a web application that showcases tech products in an interactive 3D environment. It utilizes Three.js for 3D rendering and React.js for dynamic user interface elements. The project focuses on creating a visually engaging and performant experience, allowing users to explore and interact with products in a unique way."
    },
    {
        "projectId": "5",
        "projectName": "Purrfect Paws",
        "projectHeader": "A Journey Through The Feline World, Where Curiosity Meets Discovery.",
        "projectStack": ["TypeScript"],
        "framework": ["Angular.JS"],
        "projectURL": "https://github.com/faizzmi/purrfect-paws",
        "projectLevel":"Personal",
        "createdAt": "2024-02-16T00:28:18Z",
        "projectType": "Web Development",
        "projectFeatures": "Purrfect Paws was designed to provide users with an interactive platform for learning about different cat breeds. The unique aspect of the project was its dynamic filtering system, which allowed users to select specific traits and preferences to discover the ideal cat breed for them. The most significant challenge was creating a robust filtering system that was intuitive and fast, especially when dealing with large datasets. Additionally, implementing a smooth and responsive UI with Angular.js was key to providing an engaging user experience.",
        "reflection": "This project improved my front-end development skills, especially with Angular.js and TypeScript. I learned how to build complex UIs and manage large datasets efficiently. The project also reinforced the importance of user-centered design, as I had to ensure that the app was easy to navigate and visually appealing. Despite the challenges of implementing dynamic filters and managing data, the project helped me improve my problem-solving skills and made me more confident in building interactive web applications.",
        "projectDesc": "Purrfect Paws is a web application that helps users find the perfect cat breed for them. It features a dynamic filtering system that allows users to select specific traits and preferences, such as coat color, size, and temperament. The application provides an interactive and engaging experience for users to explore the world of feline breeds."
    },
    {
        "projectId": "6",
        "projectName": "TraceTogether",
        "projectHeader": "A Digital Lifeline In The Fight For Public Health And Safety.",
        "projectStack": ["Java", "Android Studio"],
        "framework": [],
        "projectURL": "https://github.com/faizzmi/TraceTogether",
        "projectLevel":"Academic",
        "createdAt": "2024-11-07T00:00:00Z",
        "projectType": "Mobile App Development",
        "projectFeatures": "TraceTogether was developed to provide a digital contact tracing system for public health. The key feature of the app was its ability to track proximity between users and notify them of potential exposure to infectious diseases. The biggest challenge was ensuring the app was both accurate in tracking and respectful of privacy, which required a careful design of the data collection process. Ensuring the app was lightweight and efficient for a wide range of Android devices was another key concern during development.",
        "reflection": "Developing TraceTogether gave me invaluable experience in mobile app development, especially with Java and Android Studio. It highlighted the importance of balancing functionality with privacy concerns, a critical aspect when developing public health tools. The project also enhanced my ability to create efficient and scalable mobile applications, and I was proud to contribute to a project that could have a real-world impact on public health.",
        "projectDesc": "TraceTogether is a mobile application designed to assist in contact tracing efforts to help control the spread of infectious diseases. It utilizes proximity tracking technology to identify potential exposure risks while prioritizing user privacy and data security."
    },
    {
        "projectId": "7",
        "projectName": "Tribute",
        "projectHeader": "Honoring The Legacy Of A Nation’s Founding Father In Pixels And Code.",
        "projectStack": ["HTML", "CSS"],
        "framework": [],
        "projectURL": "https://github.com/faizzmi/Tribute",
        "projectLevel":"Personal",
        "createdAt": "2024-11-12T00:00:00Z",
        "projectType": "Web Development",
        "projectFeatures": "Tribute was a simple yet impactful project built to honor a historical figure through a well-designed tribute page. The project’s uniqueness lies in its focus on visual storytelling, where I used HTML and CSS to design a page that both conveyed information and evoked emotion. The challenge was ensuring that the design was both minimalistic and informative, without overwhelming the visitor with too much text or imagery. The project also required creating a clean, responsive layout that could work across different devices.",
        "reflection": "Tribute was an important project in my web development journey, as it allowed me to focus on design principles while still developing a functional website. I learned the importance of simplicity in design, ensuring that every element served a purpose. The project also helped me improve my HTML and CSS skills, particularly in creating responsive layouts and using styles effectively to guide the user’s focus.",
        "projectDesc": "Tribute is a web page dedicated to honoring a historical figure. It utilizes HTML and CSS to create a visually appealing and informative tribute, emphasizing simplicity and clarity in design."
    },
    {
        "projectId": "8",
        "projectName": "Trip Planner",
        "projectHeader": "AI-Driven Adventure Planning, Making Every Journey More Effortless And Exciting.",
        "projectStack": ["JavaScript", "Gemini"],
        "framework": ["React Native"],
        "projectURL": "https://github.com/faizzmi/trip-planner",
        "projectLevel":"Personal",
        "createdAt": "2024-12-29T09:45:43Z",
        "projectType": "Mobile App Development",
        "projectFeatures": "The Trip Planner app leverages AI to help users plan their trips with personalized recommendations. The most unique aspect of this app is its use of the Gemini AI engine to suggest destinations and activities based on the user’s preferences. The biggest challenge was integrating AI effectively into the app while keeping the UI intuitive and responsive. Ensuring the AI recommendations were accurate and useful required careful tuning of the algorithm, as well as user testing to gather feedback.",
        "reflection": "Developing Trip Planner taught me valuable lessons in AI integration, especially within mobile applications. It challenged me to think about how AI can enhance user experiences in a practical and engaging way. I also gained experience working with React Native, which helped me become more versatile as a mobile app developer. The project gave me confidence in creating intelligent, data-driven apps and reinforced my interest in exploring the intersection of AI and mobile development.",
        "projectDesc": "Trip Planner is a mobile application that utilizes AI to assist users in planning their travel itineraries. It leverages the Gemini AI engine to provide personalized recommendations for destinations and activities based on user preferences."
    },
    {
        "projectId": "9",
        "projectName": "VendPal",
        "projectHeader": "Reimagining The Vending Experience For The Modern World.",
        "projectStack": ["JavaScript"],
        "framework": [],
        "projectURL": "https://github.com/faizzmi/Vending-Machine",
        "projectLevel":"Academic",
        "createdAt": "2024-11-27T15:46:38Z",
        "projectType": "Software Development",
        "projectFeatures": "VendPal aimed at creating an enhanced vending machine experience by implementing a digital payment and interaction system. The major challenge was creating an intuitive interface for users to select products and make payments seamlessly. Another difficulty was ensuring the backend could handle simultaneous requests during peak usage times, and maintaining security for user transactions. The project was unique because it integrated traditional vending with modern digital technologies for a seamless user experience.",
        "reflection": "Developing VendPal was a great learning opportunity in web development and payment system integration. It taught me how to handle real-time transactions and manage scalability concerns, which are essential skills for handling applications in high-demand environments. The project also enhanced my understanding of integrating front-end interfaces with secure back-end services to ensure a smooth and safe user experience.",
        "projectDesc": "VendPal is a web application that modernizes the vending machine experience. It integrates digital payment options and an intuitive user interface to enhance the product selection and purchasing process."
    },
    {
        "projectId": "10",
        "projectName": "HASIL INTERNAL AUDIT SYSTEM (HIAS)",
        "projectHeader": "An Internal Audit System for LHDN to streamline audit processes.",
        "projectStack": ["TypeScript"],
        "framework": ["Angular", "Ionic"],
        "projectURL": "",
        "projectLevel":"Internship",
        "createdAt": "2025-01-16T15:00:00Z",
        "projectType": "Enterprise Software",
        "projectFeatures": "HIAS was developed to streamline the internal audit process at LHDN, automating many manual tasks and improving the overall efficiency of the department. The system needed to be highly secure, as it handled sensitive financial data. The challenge was ensuring the security of the data while maintaining usability. Another difficulty was ensuring the system could integrate smoothly with the existing infrastructure at LHDN. The system was designed to be scalable, ensuring that it could adapt to the growing needs of the department over time.",
        "reflection": "Building HIAS was a great experience in enterprise software development. I learned a lot about security, data management, and creating scalable systems that can grow with a company’s needs. The project also gave me valuable insights into the importance of designing systems that integrate well with existing infrastructure, as well as the challenges of working with sensitive data in a corporate environment.",
        "projectDesc": "HIAS is an internal audit system developed for LHDN (Lembaga Hasil Dalam Negeri) to streamline and improve the efficiency of their audit processes. The system incorporates features such as automated tasks, enhanced data security, and seamless integration with existing LHDN infrastructure."
    },
    {
        "projectId": "11",
        "projectName": "MYKKP",
        "projectHeader": "MyKKP is an online service provided by Kementerian Keselamatan dan Kesihatan Pekerja for its users.",
        "projectStack": ["JavaScript"],
        "framework": ["Angular"],
        "projectURL": "",
        "projectLevel":"Internship",
        "createdAt": "2024-03-01T00:00:00Z",
        "projectType": "Web Development",
        "projectFeatures": "MYKKP is a service designed to streamline and provide easy access to government services related to workers' health and safety. The project required the creation of a user-friendly platform that could handle large amounts of data and integrate seamlessly with existing government systems. One of the main challenges was ensuring that the platform was secure and met compliance standards, especially considering the sensitive nature of the data. Angular was used for developing a responsive and interactive frontend that allowed users to access various features with ease.",
        "reflection": "Developing MYKKP was an excellent learning experience in building enterprise-level applications. It gave me a deep understanding of how to handle sensitive data while ensuring that the platform was both secure and user-friendly. The project also required me to work with government standards and compliance requirements, which added a layer of complexity but also improved my attention to detail. This experience strengthened my skills in working with Angular and integrating large-scale systems, and provided valuable insights into building secure and reliable web platforms.",
        "projectDesc": "MYKKP is an online service developed by Kementerian Keselamatan dan Kesihatan Pekerja (Ministry of Occupational Safety and Health) to provide users with convenient access to government services related to worker safety and health."
    },
    {
        "projectId": "12",
        "projectName": "ShowCase-X",
        "projectHeader": "A personal portfolio showcasing projects and skills.",
        "projectStack": ["JavaScript"],
        "framework": ["React", "Next.js"],
        "projectURL": "",
        "projectLevel":"Personal",
        "createdAt": "2025-01-16T00:00:00Z",
        "projectType": "Web Development",
        "projectFeatures": "ShowCase-X is a personal portfolio built with React and Next.js to showcase a developer's work and skills. The unique feature of this project is the integration of a smooth and interactive user interface, powered by Next.js, to deliver a fast and SEO-friendly experience. The challenge was ensuring that the portfolio would work across various devices and browsers while maintaining optimal loading speeds. I also integrated animations and transitions to make the portfolio more engaging, which required careful optimization to ensure performance wasn’t compromised.",
        "reflection": "Building ShowCase-X was an opportunity to experiment with modern web technologies and create a dynamic, engaging personal portfolio. It allowed me to refine my React and Next.js skills, especially in terms of server-side rendering and SEO optimization. The project also helped me understand the importance of user experience, as I had to ensure the site was easy to navigate and visually appealing. This portfolio has become a great showcase for my skills and projects, and the experience of building it further solidified my web development expertise.",
        "projectDesc": "ShowCase-X is a personal portfolio website built with React and Next.js. It showcases the developer's projects, skills, and experiences, featuring a smooth and interactive user interface with a focus on fast loading times and SEO optimization."
    }
];

export const desc = 'This portfolio highlights a curated selection of my work, demonstrating the variety and scope of projects I’ve completed. While certain pieces are excluded for reasons of client confidentiality, I’m confident that these examples reflect the wide range of skills and expertise I bring to every project.'
